fix isvalidpoint
tnc-br/ddf_common pull request #27
Opened 2023-08-09 15:37 UTC by benwulfe

fixes an exception in is_valid_point.

2023-08-10 13:32 UTC, erickzul requested changes
Per offline discussion, let's have get_data_at_coords call is_valid_point and throw an exception if the result is False.

2023-08-15 23:23 UTC, benwulfe commented
should be fixed now

2023-08-16 13:17 UTC, erickzul commented
Do we need to add/run any tests for code here or in ddf-isoscaopes that depend on this?

2023-08-17 15:26 UTC, erickzul approved these changes
Approved pending confirming code runs successfully in ddf-isoscapes with these changes.

2023-08-17 19:57 UTC, benwulfe commented on raster.py
> +  value = _get_data_at_coords(dataset, x, y, month)
a naming pattern i have seen in this context is "tryX"
_try_get_value_at_coords....

seems reasonable.  though in general the underscore is usually hidden, so shouldnt be confused, i do agree the name could be clearer.

2023-08-17 20:18 UTC, benwulfe commented
I did not see anything impacted, but those could have been in branches.

2023-08-17 20:18 UTC, merged