Capture transformer + TF model in a new model.py class
tnc-br/ddf_common pull request #34
Opened 2023-08-21 18:03 UTC by VimWizardVersace

2023-08-21 18:23 UTC, erickzul requested changes

2023-08-21 18:23 UTC, erickzul commented on model.py
> +    def load_transformer(self, transformer_path: str) -> ColumnTransformer:
Could we preface private/helper class methods here load_tf_model -> _load_tf_model so we know we shouldn't expect them to be called by the user?

2023-08-21 18:52 UTC, benwulfe approved these changes
Please add doc comments to all public members
Please preface private members with underscore as luis suggests.

Approved pending those changes.

2023-08-21 18:52 UTC, benwulfe commented on model.py
> +class Model:
missing doc comments.

2023-08-22 14:17 UTC, erickzul approved these changes

2023-08-22 14:25 UTC, merged