Stamp isoscape
tnc-br/ddf_common pull request #36
Opened 2023-08-22 16:30 UTC by gretaabib

Functions to stamp isoscape created in the ddf_common.

2023-08-22 20:34 UTC, benwulfe commented on raster.py
> +def stamp_isoscape(filename, metadata_name, metadata_value):
please add proper doc comments.  looks good otherwise!

2023-08-22 20:38 UTC, benwulfe requested changes
Please add python doccomments
https://realpython.com/documenting-python-code/#class-docstrings

2023-08-24 18:40 UTC, gretaabib commented
> Please add python doccomments https://realpython.com/documenting-python-code/#class-docstrings

@benwulfe I've included the doccomments, may I commit?

2023-08-24 19:01 UTC, benwulfe approved these changes

2023-08-24 19:03 UTC, merged