Move nudging to ddf_common
tnc-br/ddf_common pull request #40
Opened 2023-09-01 19:32 UTC by VimWizardVersace

2023-09-05 14:51 UTC, erickzul requested changes
Please remove validation_pipeline.ipynb

2023-09-05 14:55 UTC, VimWizardVersace commented
> Please remove validation_pipeline.ipynb

done

2023-09-05 15:35 UTC, erickzul requested changes

2023-09-05 15:35 UTC, erickzul commented on dataset.py
> +def valid_in_all_rasters(
Please change this to _valid_in_all_rasters to reflect that this should be not used outside of this module (it's a helper method).

2023-09-05 15:35 UTC, erickzul commented on dataset.py
> +  max_degrees_deviation = 2
We want this to be an input parameter to the function. Please consider making a parameter.

2023-09-05 15:35 UTC, erickzul commented on dataset.py
> +        bool: True if (lat, lon) is valid in all rasters, False if invalid in
Please change this to:
pd.DataFrame: Returns a dataframe with nudged coordinates.

2023-09-05 15:35 UTC, erickzul commented on dataset_test.ipynb
Is there a way for us to nudge for when the nudging isn't feasible? i.e. the ValueError exception in line 526 in dataset.py

2023-09-05 20:50 UTC, VimWizardVersace commented on dataset_test.ipynb
Done

2023-09-11 13:41 UTC, erickzul approved these changes

2023-09-11 14:21 UTC, merged