Add ordinary kriging means and vars to eeraster
tnc-br/ddf_common pull request #49
Opened 2023-09-28 19:16 UTC by erickzul

2023-09-28 21:54 UTC, rothn requested changes
Looks good in principle. Minor changes requested. Please also get @benwulfe 's approval before merging due to the sensitive timing.

2023-09-28 21:54 UTC, rothn commented on eeraster.py
> +  global _ordinary_kriging_means
This is declared as a global but appears to be missing from the globals at the top of the file.

2023-09-28 21:54 UTC, rothn commented on eeraster.py
> +  global _ordinary_kriging_vars
This is declared as a global but appears to be missing from the globals at the top of the file.

2023-09-28 21:54 UTC, rothn commented on eeraster.py
> +      'projects/river-sky-386919/assets/reference_rasters/uc_davis_d18O_cel_ordinary_random_grouped_vars').select("b1"))
Do we want to explicitly reference the UAT instance here, even for production users?

2023-09-28 21:54 UTC, rothn commented on eeraster.py
> +      'projects/river-sky-386919/assets/reference_rasters/uc_davis_d18O_cel_ordinary_random_grouped_means').select("b1"))
Do we want to explicitly reference the UAT instance here, even for production users?

2023-10-03 15:32 UTC, erickzul commented
Made changes based on comments. PTAL.

2023-10-03 18:14 UTC, rothn commented
I think maybe we missed a comment-- "Do we want to explicitly reference the UAT instance here, even for production users?"

2023-10-04 16:55 UTC, erickzul commented
Used eeedf.project_name() to parameterize the project name.

2023-10-04 17:01 UTC, rothn commented
Approved! Please make sure to get @benwulfe 's OK first as this is merging into ddf_common during a period of transition.

2023-10-04 17:01 UTC, rothn approved these changes

2023-10-05 21:57 UTC, benwulfe requested changes
This looks good, but I suspect this only will work for users that are site admins that have full gcp access.  Try uploading to production timberid-prd - you probably wont be able to see it until you are added as a site admin.  We need to have this running on timberid-prd because we need to use real timberid data -- not from test.

This means only site admins can do research which is probably ok for now -- but should go away once we move to bonafide GEE rasters.

just ACK this and I will approve.

2023-10-06 15:57 UTC, benwulfe approved these changes

2023-10-06 16:01 UTC, merged